[package]
name = "portlight"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2021"
publish = false

[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.8", features = ["std", "winuser", "windef", "minwindef", "errhandlingapi", "winnt", "ntdef", "wingdi", "windowsx"] }
uuid = { version = "0.8", features = ["v4"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "0.2.7", features = ["exception"] }
cocoa = "0.24.0"
getrandom = "0.2.10"

[target.'cfg(target_os = "linux")'.dependencies]
xcb-sys = { version = "0.2.1", features = ["icccm", "shm", "cursor"] }
libc = "0.2"
