name: CI

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  ci:
    name: Build and run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install xcb dependencies (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev libxcb-icccm4-dev libxcb-cursor-dev
      - name: Build
        run: cargo build --workspace
      - name: Run tests
        run: cargo test --workspace
